// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-cards.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_cards_default = defineTool({
  name: "search_cards",
  title: "Search Pokemon cards",
  description: "Search the PokeIQ card catalog by name. Returns up to `limit` matching Pokemon cards with set, number, and rarity.",
  inputSchema: {
    query: z.string().min(1).describe("Card name or partial name to search for."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max cards to return."),
    include_sealed: z.boolean().default(false).describe("Include sealed products in results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit, include_sealed }) => {
    const client = sb();
    let q = client.from("cards_justtcg").select("id,tcgplayer_id,name,set_name,set_code,number,rarity,is_sealed,game").ilike("name", `%${query}%`).eq("game", "pokemon").limit(limit);
    if (!include_sealed) q = q.eq("is_sealed", false);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-card-prices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_card_prices_default = defineTool2({
  name: "get_card_prices",
  title: "Get card prices",
  description: "Get current market prices for all variants (condition/printing/language) of a specific card by its PokeIQ card id. Use search_cards first to find the id.",
  inputSchema: {
    card_id: z2.string().min(1).describe("The card id returned by search_cards.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ card_id }) => {
    const client = sb2();
    const [cardRes, variantsRes] = await Promise.all([
      client.from("cards_justtcg").select("id,name,set_name,number,rarity").eq("id", card_id).maybeSingle(),
      client.from("variants_justtcg").select("condition,printing,language,price_current,last_updated").eq("card_id", card_id).order("price_current", { ascending: false })
    ]);
    if (cardRes.error) {
      return { content: [{ type: "text", text: `Error: ${cardRes.error.message}` }], isError: true };
    }
    if (!cardRes.data) {
      return { content: [{ type: "text", text: `No card with id ${card_id}` }], isError: true };
    }
    const payload = { card: cardRes.data, variants: variantsRes.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-trending-pokemon.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trending_pokemon_default = defineTool3({
  name: "list_trending_pokemon",
  title: "List trending Pokemon",
  description: "Return the top trending Pokemon over the last 7 days, ranked by average price change across their cards (PokeIQ Greatest Hits index).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(15).describe("Max Pokemon to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const client = sb3();
    const { data: latest } = await client.from("greatest_hits_cache").select("snapshot_date").order("snapshot_date", { ascending: false }).limit(1).maybeSingle();
    if (!latest?.snapshot_date) {
      return { content: [{ type: "text", text: "No trending data available." }], structuredContent: { trending: [] } };
    }
    const { data, error } = await client.from("greatest_hits_cache").select("pokemon_name,avg_change_7d,card_count").eq("snapshot_date", latest.snapshot_date).order("avg_change_7d", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const payload = { snapshot_date: latest.snapshot_date, trending: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pokeiq-mcp",
  title: "PokeIQ MCP",
  version: "0.1.0",
  instructions: "Tools for the PokeIQ Pokemon card market intelligence app. Use `search_cards` to find cards by name, `get_card_prices` to look up current market prices for a card's variants, and `list_trending_pokemon` to see which Pokemon are hottest over the last 7 days.",
  tools: [search_cards_default, get_card_prices_default, list_trending_pokemon_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
